import './globals.css'
import Nav from './nav'
import {Roboto} from 'next/font/google';

const roboto = Roboto({
    weight: ['400', '700'],
    subsets: ['latin']
})

export const metadata = {
  title: 'Puppy App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">        
        <body className={roboto.className}>
            <Nav/>
            <div>
            {children}
            </div>
        </body>
    </html>
  )
}
